export interface TurtleCommand {
  type: 'up' | 'down' | 'fd' | 'seth' | 'circle' | 'pensize' | 'color' | 'begin_fill' | 'end_fill' | 'ht';
  args?: number[];
  color?: string;
}

export interface TurtleInstructionSet {
  name: string;
  color: string;
  commands: TurtleCommand[];
}

export const RADHA_KRISHNA_TURTLE_SCRIPT: TurtleInstructionSet[] = [
  // Turtle b: Radha
  {
    name: 'Radha',
    color: '#FFD700', // Gold yellow
    commands: [
      { type: 'up' },
      { type: 'seth', args: [0] },
      { type: 'fd', args: [22] },
      { type: 'seth', args: [90] },
      { type: 'fd', args: [103] },
      { type: 'pensize', args: [5] },
      { type: 'down' },
      { type: 'seth', args: [10] },
      { type: 'circle', args: [-50, 25] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-50, 10] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-50, 5] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [-50, 3] },
      { type: 'up' },
      { type: 'seth', args: [180] },
      { type: 'fd', args: [35] },
      { type: 'seth', args: [-90] },
      { type: 'fd', args: [14] },
      { type: 'down' },

      // eye1
      { type: 'seth', args: [-46] },
      { type: 'fd', args: [5] },
      { type: 'pensize', args: [3] },
      { type: 'fd', args: [10] },
      { type: 'pensize', args: [4] },
      { type: 'fd', args: [4] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [25, 62] },
      { type: 'pensize', args: [4] },
      { type: 'seth', args: [-48] },
      { type: 'fd', args: [3] },
      { type: 'pensize', args: [3] },
      { type: 'fd', args: [4] },
      { type: 'pensize', args: [2] },
      { type: 'fd', args: [3] },
      { type: 'up' },
      { type: 'seth', args: [45] },
      { type: 'fd', args: [63] },
      { type: 'down' },

      { type: 'circle', args: [-100, 3] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-100, 8] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-100, 9] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-100, 13] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-100, 8] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-100, 6] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [-100, 3] },

      { type: 'up' },
      { type: 'seth', args: [-139] },
      { type: 'fd', args: [103] },
      { type: 'down' },

      // eye2
      { type: 'seth', args: [46] },
      { type: 'fd', args: [4] },
      { type: 'pensize', args: [3] },
      { type: 'fd', args: [6] },
      { type: 'pensize', args: [4] },
      { type: 'fd', args: [6] },
      { type: 'seth', args: [-5] },
      { type: 'circle', args: [115, 5] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [115, 10] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [115, 15] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [115, 10] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [115, 5] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [115, 5] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [115, 5] },

      { type: 'up' },
      { type: 'seth', args: [176] },
      { type: 'fd', args: [142] },
      { type: 'down' },

      // pottu / tilak
      { type: 'pensize', args: [7] },
      { type: 'circle', args: [2, 360] },

      { type: 'pensize', args: [4] },
      { type: 'up' },
      { type: 'seth', args: [-94] },
      { type: 'fd', args: [118] },
      { type: 'down' },

      { type: 'seth', args: [-125] },
      { type: 'circle', args: [15, 85] },
      { type: 'fd', args: [10] },

      { type: 'pensize', args: [3] },
      { type: 'up' },
      { type: 'seth', args: [-115] },
      { type: 'fd', args: [22] },
      { type: 'down' },

      { type: 'seth', args: [28] },
      { type: 'fd', args: [15] },
      { type: 'circle', args: [-9, 85] },
      { type: 'seth', args: [75] },
      { type: 'circle', args: [-9, 83] },
      { type: 'circle', args: [40, 48] },
      { type: 'seth', args: [-131] },
      { type: 'circle', args: [-65, 62] },

      { type: 'up' },
      { type: 'seth', args: [-70] },
      { type: 'fd', args: [6] },
      { type: 'down' },
      { type: 'seth', args: [-34] },
      { type: 'circle', args: [35, 80] },

      { type: 'pensize', args: [2] },
      { type: 'up' },
      { type: 'seth', args: [150] },
      { type: 'fd', args: [99] },
      { type: 'down' },

      { type: 'seth', args: [-67] },
      { type: 'fd', args: [10] },
      { type: 'pensize', args: [3] },
      { type: 'fd', args: [40] },
      { type: 'circle', args: [122, 36] },
      { type: 'seth', args: [0] },
      { type: 'fd', args: [27] },
      { type: 'seth', args: [27] },
      { type: 'circle', args: [220, 40] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [220, 5] },

      { type: 'pensize', args: [3] },
      { type: 'up' },
      { type: 'seth', args: [-60] },
      { type: 'fd', args: [10] },
      { type: 'down' },

      { type: 'seth', args: [-90] },
      { type: 'fd', args: [32] },
      { type: 'seth', args: [0] },
      { type: 'circle', args: [-25, 160] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-25, 100] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-25, 50] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-25, 35] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-25, 15] },

      { type: 'pensize', args: [3] },
      { type: 'up' },
      { type: 'seth', args: [-10] },
      { type: 'fd', args: [40] },
      { type: 'down' },

      { type: 'seth', args: [-90] },
      { type: 'fd', args: [14] },
      { type: 'seth', args: [0] },
      { type: 'circle', args: [-10, 160] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-10, 100] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-10, 50] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-10, 35] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-10, 15] },

      { type: 'pensize', args: [4] },
      { type: 'up' },
      { type: 'seth', args: [147] },
      { type: 'fd', args: [315] },
      { type: 'down' },

      { type: 'seth', args: [90] },
      { type: 'circle', args: [-120, 5] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-120, 40] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-45, 50] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-45, 42] },
      { type: 'fd', args: [70] },
      { type: 'seth', args: [-38] },
      { type: 'fd', args: [50] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-75, 44] },
      { type: 'fd', args: [50] },
      { type: 'circle', args: [70, 48] },
      { type: 'seth', args: [-5] },
      { type: 'pensize', args: [4] },
      { type: 'fd', args: [20] },
      { type: 'circle', args: [-7, 82] },
      { type: 'pensize', args: [3] },
      { type: 'fd', args: [25] },
      { type: 'circle', args: [-60, 33] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [-60, 10] },

      { type: 'pensize', args: [1] },
      { type: 'up' },
      { type: 'seth', args: [-90] },
      { type: 'fd', args: [15] },
      { type: 'seth', args: [-179] },
      { type: 'fd', args: [212] },
      { type: 'down' },

      // hair2
      { type: 'pensize', args: [7] },
      { type: 'seth', args: [80] },
      { type: 'circle', args: [30, 51] },
      { type: 'pensize', args: [4] },
      { type: 'fd', args: [18] },
      { type: 'pensize', args: [7] },
      { type: 'seth', args: [150] },
      { type: 'circle', args: [-50, 37] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [-250, 13] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-250, 6] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-250, 4] },

      { type: 'pensize', args: [1] },
      { type: 'up' },
      { type: 'seth', args: [56] },
      { type: 'fd', args: [238] },
      { type: 'down' },

      { type: 'pensize', args: [4] },
      { type: 'seth', args: [-2] },
      { type: 'circle', args: [-100, 31] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [-100, 31] },
      { type: 'fd', args: [80] },
      { type: 'pensize', args: [4] },
      { type: 'fd', args: [45] },

      { type: 'pensize', args: [1] },
      { type: 'up' },
      { type: 'seth', args: [133] },
      { type: 'fd', args: [100] },
      { type: 'down' },

      { type: 'seth', args: [-78] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [132, 5] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [132, 10] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [132, 20] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [132, 20] },
      { type: 'circle', args: [-120, 20] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-120, 10] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-120, 8] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [-120, 7] },

      { type: 'pensize', args: [1] },
      { type: 'up' },
      { type: 'seth', args: [144] },
      { type: 'fd', args: [368] },
      { type: 'down' },

      // hair5 fill
      { type: 'begin_fill' },
      { type: 'seth', args: [45] },
      { type: 'circle', args: [-35, 92] },
      { type: 'fd', args: [70] },
      { type: 'seth', args: [-42] },
      { type: 'fd', args: [30] },
      { type: 'circle', args: [-80, 14] },
      { type: 'fd', args: [60] },
      { type: 'seth', args: [152] },
      { type: 'circle', args: [-220, 27] },
      { type: 'seth', args: [115] },
      { type: 'circle', args: [220, 20] },
      { type: 'circle', args: [2, 176] },
      { type: 'circle', args: [-150, 25] },
      { type: 'circle', args: [281, 27] },
      { type: 'seth', args: [138] },
      { type: 'circle', args: [-280, 26] },
      { type: 'circle', args: [280, 16] },
      { type: 'circle', args: [24, 65] },
      { type: 'end_fill' },
      { type: 'ht' }
    ]
  },

  // Turtle c: Krishna
  {
    name: 'Krishna',
    color: '#FFD700',
    commands: [
      { type: 'up' },
      { type: 'seth', args: [166] },
      { type: 'fd', args: [200] },
      { type: 'down' },

      // eye1
      { type: 'pensize', args: [4] },
      { type: 'seth', args: [150] },
      { type: 'circle', args: [70, 13] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [70, 10] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [70, 10] },
      { type: 'pensize', args: [7] },
      { type: 'circle', args: [70, 15] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [70, 8] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [70, 7] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [70, 5] },

      { type: 'up' },
      { type: 'seth', args: [-19.5] },
      { type: 'fd', args: [104] },
      { type: 'down' },

      { type: 'pensize', args: [5] },
      { type: 'seth', args: [137] },
      { type: 'fd', args: [8] },
      { type: 'pensize', args: [4] },
      { type: 'fd', args: [5] },
      { type: 'circle', args: [8, 92] },
      { type: 'circle', args: [-37, 26] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-37, 20] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [-37, 10] },
      { type: 'pensize', args: [7] },
      { type: 'circle', args: [-37, 10] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [-37, 10] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-37, 10] },
      { type: 'pensize', args: [3] },
      { type: 'fd', args: [8] },
      { type: 'pensize', args: [2] },
      { type: 'fd', args: [7] },
      { type: 'pensize', args: [1] },
      { type: 'fd', args: [5] },

      { type: 'up' },
      { type: 'seth', args: [17.5] },
      { type: 'fd', args: [123] },
      { type: 'down' },

      // eye2
      { type: 'pensize', args: [5] },
      { type: 'seth', args: [58] },
      { type: 'circle', args: [-80, 5] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [-80, 10] },
      { type: 'pensize', args: [7] },
      { type: 'circle', args: [-80, 15] },
      { type: 'pensize', args: [8] },
      { type: 'circle', args: [-80, 15] },
      { type: 'pensize', args: [7] },
      { type: 'circle', args: [-80, 10] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [-80, 8] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-80, 7] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-80, 5] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [-80, 3] },
      { type: 'pensize', args: [1] },
      { type: 'circle', args: [-80, 2] },

      { type: 'up' },
      { type: 'seth', args: [-139] },
      { type: 'fd', args: [118] },
      { type: 'down' },

      { type: 'pensize', args: [5] },
      { type: 'seth', args: [68] },
      { type: 'fd', args: [6] },
      { type: 'pensize', args: [4] },
      { type: 'fd', args: [3] },
      { type: 'pensize', args: [3] },
      { type: 'fd', args: [6] },
      { type: 'circle', args: [-12, 57] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-12, 20] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-12, 10] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [45, 30] },
      { type: 'pensize', args: [7] },
      { type: 'circle', args: [45, 20] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [45, 15] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [45, 8] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [45, 7] },
      { type: 'fd', args: [17] },
      { type: 'pensize', args: [2] },
      { type: 'fd', args: [10] },

      { type: 'up' },
      { type: 'seth', args: [163] },
      { type: 'fd', args: [165] },
      { type: 'down' },

      // pottu / tilak
      { type: 'seth', args: [-10] },
      { type: 'pensize', args: [4] },
      { type: 'fd', args: [5] },
      { type: 'seth', args: [-45] },
      { type: 'circle', args: [-50, 30] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-50, 10] },
      { type: 'pensize', args: [6] },
      { type: 'fd', args: [15] },
      { type: 'circle', args: [45, 39] },
      { type: 'circle', args: [7, 138] },
      { type: 'pensize', args: [7] },
      { type: 'fd', args: [30] },
      { type: 'pensize', args: [6] },
      { type: 'fd', args: [20] },
      { type: 'pensize', args: [5] },
      { type: 'fd', args: [10] },
      { type: 'pensize', args: [4] },
      { type: 'fd', args: [5] },
      { type: 'circle', args: [-18, 35] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-18, 20] },

      { type: 'up' },
      { type: 'seth', args: [-89.5] },
      { type: 'fd', args: [167] },
      { type: 'down' },

      // nose
      { type: 'circle', args: [45, 40] },

      { type: 'up' },
      { type: 'seth', args: [-120] },
      { type: 'fd', args: [31] },
      { type: 'down' },

      // mouth
      { type: 'seth', args: [27] },
      { type: 'fd', args: [18] },
      { type: 'circle', args: [-9, 85] },
      { type: 'seth', args: [78] },
      { type: 'circle', args: [-10, 98] },
      { type: 'circle', args: [25, 80] },
      { type: 'seth', args: [-127] },
      { type: 'circle', args: [-67, 68] },

      { type: 'up' },
      { type: 'seth', args: [-35] },
      { type: 'fd', args: [13] },
      { type: 'down' },
      { type: 'seth', args: [-30] },
      { type: 'circle', args: [37, 85] },

      { type: 'pensize', args: [1] },
      { type: 'up' },
      { type: 'seth', args: [151.5] },
      { type: 'fd', args: [270] },
      { type: 'down' },

      // head1 fill
      { type: 'begin_fill' },
      { type: 'seth', args: [127] },
      { type: 'circle', args: [-90, 43] },
      { type: 'seth', args: [45.5] },
      { type: 'fd', args: [118] },
      { type: 'circle', args: [-1, 165] },
      { type: 'fd', args: [74] },
      { type: 'circle', args: [25, 45] },
      { type: 'seth', args: [-111] },
      { type: 'fd', args: [50] },
      { type: 'seth', args: [-40] },
      { type: 'fd', args: [10] },
      { type: 'seth', args: [61] },
      { type: 'fd', args: [100] },
      { type: 'circle', args: [-185, 32] },
      { type: 'circle', args: [1, 175] },
      { type: 'circle', args: [200, 37] },
      { type: 'circle', args: [-2.5, 180] },
      { type: 'fd', args: [48] },
      { type: 'seth', args: [60] },
      { type: 'circle', args: [-180, 58] },
      { type: 'seth', args: [173] },
      { type: 'circle', args: [150, 60] },
      { type: 'seth', args: [-155] },
      { type: 'circle', args: [238, 33] },
      { type: 'seth', args: [-92] },
      { type: 'circle', args: [95, 43] },
      { type: 'end_fill' },

      { type: 'up' },
      { type: 'seth', args: [23] },
      { type: 'fd', args: [55] },
      { type: 'down' },

      // head2 fill
      { type: 'begin_fill' },
      { type: 'seth', args: [52] },
      { type: 'circle', args: [-400, 24] },
      { type: 'seth', args: [-165] },
      { type: 'circle', args: [200, 50] },
      { type: 'end_fill' },

      { type: 'up' },
      { type: 'seth', args: [38] },
      { type: 'fd', args: [150] },
      { type: 'down' },

      // head3 fill
      { type: 'begin_fill' },
      { type: 'seth', args: [2] },
      { type: 'circle', args: [-180, 20] },
      { type: 'seth', args: [133] },
      { type: 'circle', args: [55, 70] },
      { type: 'end_fill' },

      { type: 'up' },
      { type: 'seth', args: [9] },
      { type: 'fd', args: [152] },
      { type: 'down' },

      // head4 fill
      { type: 'begin_fill' },
      { type: 'seth', args: [-20] },
      { type: 'circle', args: [-50, 98] },
      { type: 'seth', args: [80] },
      { type: 'circle', args: [70, 65] },
      { type: 'end_fill' },

      { type: 'up' },
      { type: 'seth', args: [-91] },
      { type: 'fd', args: [80] },
      { type: 'down' },

      // hair curls
      { type: 'seth', args: [-35] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-25, 45] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-25, 50] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-10, 70] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-18, 80] },
      { type: 'circle', args: [-11, 150] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-11, 60] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-11, 30] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [-11, 20] },
      { type: 'pensize', args: [1] },
      { type: 'circle', args: [-11, 10] },

      { type: 'up' },
      { type: 'seth', args: [32] },
      { type: 'fd', args: [29] },
      { type: 'down' },

      { type: 'seth', args: [24] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-25, 45] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-25, 50] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-11, 70] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-19, 80] },
      { type: 'circle', args: [-12, 150] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-12, 60] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-12, 30] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [-12, 20] },
      { type: 'pensize', args: [1] },
      { type: 'circle', args: [-12, 10] },

      { type: 'up' },
      { type: 'seth', args: [170] },
      { type: 'fd', args: [31] },
      { type: 'down' },

      { type: 'seth', args: [-33] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-48, 45] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-48, 50] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-22, 90] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [-30, 95] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [-20, 150] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [-20, 60] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [-20, 30] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [-20, 20] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [-20, 10] },

      { type: 'up' },
      { type: 'seth', args: [169] },
      { type: 'fd', args: [245] },
      { type: 'down' },

      // other hair curls
      { type: 'seth', args: [-155] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [25, 45] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [25, 50] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [10, 85] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [16, 70] },
      { type: 'circle', args: [10, 150] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [10, 60] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [10, 30] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [10, 20] },
      { type: 'pensize', args: [1] },
      { type: 'circle', args: [10, 10] },

      { type: 'up' },
      { type: 'seth', args: [167] },
      { type: 'fd', args: [23] },
      { type: 'down' },

      { type: 'seth', args: [168] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [25, 45] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [25, 50] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [12, 85] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [19, 70] },
      { type: 'circle', args: [11, 150] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [11, 60] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [11, 30] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [11, 20] },
      { type: 'pensize', args: [1] },
      { type: 'circle', args: [11, 10] },

      { type: 'up' },
      { type: 'seth', args: [21] },
      { type: 'fd', args: [30] },
      { type: 'down' },

      { type: 'seth', args: [-148] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [48, 40] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [48, 50] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [22, 90] },
      { type: 'pensize', args: [7] },
      { type: 'circle', args: [30, 95] },
      { type: 'pensize', args: [6] },
      { type: 'circle', args: [20, 150] },
      { type: 'pensize', args: [5] },
      { type: 'circle', args: [20, 60] },
      { type: 'pensize', args: [4] },
      { type: 'circle', args: [20, 30] },
      { type: 'pensize', args: [3] },
      { type: 'circle', args: [20, 20] },
      { type: 'pensize', args: [2] },
      { type: 'circle', args: [20, 10] },

      { type: 'up' },
      { type: 'seth', args: [33] },
      { type: 'fd', args: [258] },
      { type: 'down' },

      // Peacock feather (Morpankh)
      { type: 'pensize', args: [3] },
      { type: 'seth', args: [85] },
      { type: 'circle', args: [150, 25] },

      { type: 'pensize', args: [1] },
      { type: 'up' },
      { type: 'seth', args: [-88] },
      { type: 'fd', args: [42] },
      { type: 'down' },

      { type: 'begin_fill' },
      { type: 'seth', args: [131] },
      { type: 'circle', args: [-75, 45] },
      { type: 'circle', args: [-12, 150] },
      { type: 'circle', args: [-85, 35] },
      { type: 'seth', args: [88] },
      { type: 'circle', args: [75, 34] },
      { type: 'circle', args: [5, 137] },
      { type: 'circle', args: [75, 40] },
      { type: 'end_fill' },

      { type: 'up' },
      { type: 'seth', args: [135] },
      { type: 'fd', args: [15] },
      { type: 'down' },

      { type: 'begin_fill' },
      { type: 'seth', args: [140] },
      { type: 'circle', args: [-65, 77] },
      { type: 'circle', args: [-20, 125] },
      { type: 'circle', args: [-85, 45] },
      { type: 'seth', args: [84] },
      { type: 'circle', args: [75, 32] },
      { type: 'circle', args: [15, 140] },
      { type: 'circle', args: [65, 47] },
      { type: 'end_fill' },

      { type: 'up' },
      { type: 'seth', args: [-110] },
      { type: 'fd', args: [4] },
      { type: 'down' },

      { type: 'begin_fill' },
      { type: 'seth', args: [140] },
      { type: 'circle', args: [-70, 70] },
      { type: 'circle', args: [-28, 145] },
      { type: 'circle', args: [-85, 27] },
      { type: 'seth', args: [54] },
      { type: 'circle', args: [50, 50] },
      { type: 'circle', args: [-30, 60] },
      { type: 'seth', args: [-140] },
      { type: 'circle', args: [50, 35] },
      { type: 'seth', args: [74] },
      { type: 'circle', args: [100, 36] },
      { type: 'seth', args: [-82] },
      { type: 'circle', args: [-70, 35] },
      { type: 'seth', args: [92] },
      { type: 'circle', args: [55, 50] },
      { type: 'circle', args: [-35, 65] },
      { type: 'seth', args: [-135] },
      { type: 'circle', args: [125, 70] },
      { type: 'seth', args: [140] },
      { type: 'circle', args: [-80, 50] },
      { type: 'seth', args: [-94] },
      { type: 'circle', args: [100, 70] },
      { type: 'end_fill' },
      { type: 'ht' }
    ]
  },

  // Turtle d: Flute (Bansuri)
  {
    name: 'Flute',
    color: '#FFD700',
    commands: [
      { type: 'up' },
      { type: 'seth', args: [-159] },
      { type: 'fd', args: [296] },
      { type: 'down' },

      { type: 'pensize', args: [3] },
      { type: 'seth', args: [-90] },
      { type: 'begin_fill' },
      { type: 'fd', args: [18] },
      { type: 'seth', args: [-179] },
      { type: 'fd', args: [20] },
      { type: 'seth', args: [90] },
      { type: 'fd', args: [18] },
      { type: 'seth', args: [1] },
      { type: 'fd', args: [20] },
      { type: 'end_fill' },

      { type: 'fd', args: [550] },
      { type: 'seth', args: [-90] },
      { type: 'fd', args: [18] },
      { type: 'seth', args: [-179] },
      { type: 'fd', args: [550] },
      { type: 'seth', args: [90] },
      { type: 'fd', args: [18] },

      { type: 'pensize', args: [1] },
      { type: 'seth', args: [1] },
      { type: 'fd', args: [115] },

      // Flute Holes
      { type: 'seth', args: [-50] },
      { type: 'begin_fill' },
      { type: 'circle', args: [18, 103] },
      { type: 'end_fill' },

      { type: 'seth', args: [1] },
      { type: 'fd', args: [91] },

      { type: 'seth', args: [-50] },
      { type: 'begin_fill' },
      { type: 'circle', args: [18, 103] },
      { type: 'end_fill' },

      { type: 'seth', args: [1] },
      { type: 'fd', args: [35] },

      { type: 'seth', args: [-50] },
      { type: 'begin_fill' },
      { type: 'circle', args: [18, 103] },
      { type: 'end_fill' },

      { type: 'seth', args: [1] },
      { type: 'fd', args: [35] },

      { type: 'seth', args: [-50] },
      { type: 'begin_fill' },
      { type: 'circle', args: [18, 103] },
      { type: 'end_fill' },

      { type: 'seth', args: [1] },
      { type: 'fd', args: [35] },

      { type: 'seth', args: [-50] },
      { type: 'begin_fill' },
      { type: 'circle', args: [18, 100] },
      { type: 'end_fill' },

      { type: 'seth', args: [1] },
      { type: 'fd', args: [99] },

      { type: 'seth', args: [-90] },
      { type: 'fd', args: [18] },
      { type: 'seth', args: [-179] },
      { type: 'fd', args: [550] },
      { type: 'seth', args: [90] },
      { type: 'fd', args: [18] },
      { type: 'seth', args: [1] },
      { type: 'fd', args: [550] },

      { type: 'seth', args: [-90] },
      { type: 'fd', args: [1] },

      // Flute hanging tassel / decoration
      { type: 'begin_fill' },
      { type: 'seth', args: [1] },
      { type: 'fd', args: [15] },
      { type: 'seth', args: [90] },
      { type: 'fd', args: [5] },
      { type: 'circle', args: [-7, 115] },
      { type: 'fd', args: [55] },
      { type: 'seth', args: [-162] },
      { type: 'fd', args: [55] },
      { type: 'circle', args: [-7, 115] },
      { type: 'fd', args: [5] },
      { type: 'seth', args: [-179] },
      { type: 'fd', args: [15] },
      { type: 'end_fill' },

      { type: 'pensize', args: [5] },
      { type: 'up' },
      { type: 'seth', args: [-90] },
      { type: 'fd', args: [1] },
      { type: 'seth', args: [-179] },
      { type: 'fd', args: [47] },
      { type: 'down' },

      { type: 'begin_fill' },
      { type: 'seth', args: [-110] },
      { type: 'circle', args: [-130, 90] },
      { type: 'circle', args: [500, 50] },
      { type: 'seth', args: [20] },
      { type: 'circle', args: [-400, 46] },
      { type: 'circle', args: [204, 101] },
      { type: 'end_fill' },
      { type: 'ht' }
    ]
  }
];
